import type { GlobalConfig } from 'payload'

export const Events: GlobalConfig = {
  slug: 'events',
  admin: { description: 'The /events page.' },
  access: { read: () => true },
  fields: [
    {
      type: 'group',
      name: 'hero',
      label: 'Banner (hero + marquee)',
      fields: [
        { name: 'badgeLabel', type: 'text', required: true },
        { name: 'badgeMonogram', type: 'text', required: true, defaultValue: 'VE' },
        { name: 'headline', type: 'text', required: true },
        { name: 'sub', type: 'textarea', required: true },
        {
          type: 'row',
          fields: [
            { name: 'primaryCtaLabel', type: 'text', admin: { width: '25%' } },
            { name: 'primaryCtaHref', type: 'text', admin: { width: '25%' } },
            { name: 'secondaryCtaLabel', type: 'text', admin: { width: '25%' } },
            { name: 'secondaryCtaHref', type: 'text', admin: { width: '25%' } },
          ],
        },
        {
          name: 'marqueeItems',
          type: 'array',
          minRows: 1,
          fields: [{ name: 'text', type: 'text', required: true }],
          admin: { description: 'Scrolling marquee labels, e.g. "Birthdays", "Corporate Events".' },
        },
      ],
    },
    {
      type: 'group',
      name: 'eventsWeHost',
      label: 'Events We Host (expanding panels)',
      fields: [
        { name: 'eyebrow', type: 'text', required: true },
        { name: 'heading', type: 'text', required: true },
        { name: 'sub', type: 'text' },
        {
          name: 'items',
          label: 'Panels',
          type: 'array',
          minRows: 1,
          fields: [
            { name: 'image', type: 'upload', relationTo: 'media', required: true },
            { name: 'number', type: 'text', required: true },
            { name: 'title', type: 'text', required: true },
            { name: 'description', type: 'textarea', required: true },
          ],
        },
      ],
    },
    {
      type: 'group',
      name: 'venueFeatures',
      label: 'Venue Features (zebra ledger)',
      fields: [
        { name: 'eyebrow', type: 'text', required: true },
        { name: 'heading', type: 'text', required: true },
        {
          name: 'items',
          label: 'Rows',
          type: 'array',
          minRows: 1,
          fields: [
            {
              name: 'icon',
              type: 'select',
              required: true,
              options: [
                { label: 'Open Lawns', value: 'lawns' },
                { label: 'Covered Pavilion', value: 'pavilion' },
                { label: 'Sound & Lighting', value: 'lighting' },
                { label: 'Parking', value: 'parking' },
                { label: 'Catering', value: 'catering' },
                { label: 'Overnight Stay', value: 'stay' },
              ],
            },
            { name: 'title', type: 'text', required: true },
            { name: 'description', type: 'textarea', required: true },
          ],
        },
      ],
    },
    {
      type: 'group',
      name: 'gallery',
      label: 'Event Gallery (collage)',
      fields: [
        { name: 'eyebrow', type: 'text', required: true },
        { name: 'heading', type: 'text', required: true },
        {
          name: 'items',
          label: 'Photos',
          type: 'array',
          minRows: 1,
          fields: [
            { name: 'image', type: 'upload', relationTo: 'media', required: true },
            { name: 'caption', type: 'text' },
          ],
        },
      ],
    },
    {
      type: 'group',
      name: 'customise',
      label: 'Customisation Options (chip clusters)',
      fields: [
        { name: 'eyebrow', type: 'text', required: true },
        { name: 'heading', type: 'text', required: true },
        { name: 'sub', type: 'text' },
        {
          name: 'groups',
          type: 'array',
          minRows: 1,
          fields: [
            { name: 'groupNumber', type: 'text', required: true },
            { name: 'groupLabel', type: 'text', required: true },
            {
              name: 'chips',
              type: 'array',
              minRows: 1,
              fields: [{ name: 'label', type: 'text', required: true }],
            },
          ],
        },
      ],
    },
    {
      type: 'group',
      name: 'enquiry',
      label: 'Enquiry Form',
      fields: [
        { name: 'eyebrow', type: 'text', required: true },
        { name: 'heading', type: 'text', required: true },
        { name: 'sub', type: 'textarea' },
        { name: 'nameLabel', type: 'text', defaultValue: 'Your Name' },
        { name: 'namePlaceholder', type: 'text', defaultValue: 'first and last name' },
        { name: 'eventTypeLabel', type: 'text', defaultValue: 'Event Type' },
        { name: 'eventTypeNote', type: 'text', defaultValue: 'birthday, corporate, alumni, pre-wedding…' },
        { name: 'eventTypePlaceholder', type: 'text', defaultValue: 'e.g. corporate offsite' },
        { name: 'guestCountLabel', type: 'text', defaultValue: 'Guest Count' },
        { name: 'guestCountPlaceholder', type: 'text', defaultValue: 'approximate number' },
        { name: 'preferredDateLabel', type: 'text', defaultValue: 'Preferred Date' },
        { name: 'preferredDatePlaceholder', type: 'text', defaultValue: 'e.g. 14 june, or a flexible weekend' },
        { name: 'reachLabel', type: 'text', defaultValue: 'How To Reach You' },
        { name: 'reachPlaceholder', type: 'text', defaultValue: 'email or phone' },
        { name: 'moreLabel', type: 'text', defaultValue: 'Tell Us More' },
        { name: 'moreNote', type: 'text', defaultValue: 'optional' },
        { name: 'morePlaceholder', type: 'text', defaultValue: 'anything about the occasion that would help us plan' },
        { name: 'submitLabel', type: 'text', defaultValue: 'Send Enquiry →' },
        { name: 'submitNote', type: 'text', defaultValue: "We'll write back within 24 hours." },
      ],
    },
  ],
}
