/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    stays: Stay;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    stays: StaysSelect<false> | StaysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    footer: Footer;
    home: Home;
    about: About;
    contact: Contact;
    events: Event;
    faqs: Faq;
    'farm-dining': FarmDining;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'farm-dining': FarmDiningSelect<false> | FarmDiningSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image — used for accessibility and shown if the image fails to load.
   */
  alt: string;
  /**
   * Optional caption, used by gallery-style sections that display a caption under the image.
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * The three properties: Mango House, Stone House, Full House. Each is one document here and gets its own page (/mango-house, /stone-house, /full-house) plus a card on the /stay overview page. Which visual layout each section uses (bento grid, alternating rows, mosaic, etc.) is chosen in code per page — this is just the content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stays".
 */
export interface Stay {
  id: number;
  /**
   * Determines the route: /mango-house, /stone-house, or /full-house.
   */
  slug: 'mango-house' | 'stone-house' | 'full-house';
  title: string;
  tagline: string;
  /**
   * e.g. "Stay / Mango House"
   */
  heroBadgeLabel: string;
  heroImage: number | Media;
  priceFrom: number;
  /**
   * e.g. "includes breakfast, chai & farm dinner"
   */
  priceNote?: string | null;
  /**
   * e.g. "2–3 adults"
   */
  capacity: string;
  /**
   * e.g. "2 night minimum"
   */
  minNights: string;
  description: {
    intro: string;
    pullQuote: string;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  highlights?:
    | {
        title: string;
        body: string;
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  amenities?:
    | {
        title: string;
        body: string;
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  gallery?:
    | {
        image: number | Media;
        caption: string;
        id?: string | null;
      }[]
    | null;
  idealFor?:
    | {
        title: string;
        body: string;
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  finalCtaNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'stays';
        value: number | Stay;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stays_select".
 */
export interface StaysSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  tagline?: T;
  heroBadgeLabel?: T;
  heroImage?: T;
  priceFrom?: T;
  priceNote?: T;
  capacity?: T;
  minNights?: T;
  description?:
    | T
    | {
        intro?: T;
        pullQuote?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  highlights?:
    | T
    | {
        title?: T;
        body?: T;
        image?: T;
        id?: T;
      };
  amenities?:
    | T
    | {
        title?: T;
        body?: T;
        image?: T;
        id?: T;
      };
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  idealFor?:
    | T
    | {
        title?: T;
        body?: T;
        image?: T;
        id?: T;
      };
  finalCtaNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Site-wide defaults used for SEO tags and referenced across multiple pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  defaultSeoTitle: string;
  defaultSeoDescription: string;
  defaultOgImage?: (number | null) | Media;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The shared nav bar — logo, primary links (Stay has a dropdown), and the "Hold a Date" CTA.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  logo: {
    icon?: (number | null) | Media;
    wordmark: string;
  };
  primaryLinks?:
    | {
        label: string;
        href: string;
        submenu?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  cta: {
    label: string;
    href: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The one shared footer used on every page (standardized from the richer Footer.html component — the 5 different per-page inline footers in the old HTML are retired).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  ctaBanner: {
    heading: string;
    body: string;
    buttonLabel: string;
    buttonHref: string;
  };
  brand: {
    logo?: (number | null) | Media;
    tagline: string;
    note?: string | null;
  };
  quickLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  contactInfo?:
    | {
        label: string;
        value: string;
        isLink?: boolean | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        label: string;
        href: string;
        platform?: ('instagram' | 'facebook' | 'whatsapp' | 'newsletter') | null;
        id?: string | null;
      }[]
    | null;
  legalLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  copyrightText: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The / homepage. DRAFT SCHEMA — Home.html is the largest source file and this was written from partial context rather than a full section-by-section read. Treat these fields as a reasonable starting point; expect to adjust when the Home page is actually built.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  hero: {
    badge?: string | null;
    headline: string;
    sub?: string | null;
    backgroundImage?: (number | null) | Media;
    primaryCtaLabel?: string | null;
    primaryCtaHref?: string | null;
    secondaryCtaLabel?: string | null;
    secondaryCtaHref?: string | null;
  };
  staysTeaser?: {
    heading?: string | null;
    sub?: string | null;
    /**
     * Which Stays documents to feature here, and in what order.
     */
    featuredStays?: (number | Stay)[] | null;
  };
  experience?: {
    heading?: string | null;
    sub?: string | null;
    items?:
      | {
          image: number | Media;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  finalCta?: {
    heading?: string | null;
    body?: string | null;
    buttonLabel?: string | null;
    buttonHref?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The /about page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  manifesto: {
    eyebrow: string;
    headline: string;
    sub: string;
    primaryCtaLabel?: string | null;
    primaryCtaHref?: string | null;
    secondaryCtaLabel?: string | null;
    secondaryCtaHref?: string | null;
  };
  story?: {
    wordGlosses?:
      | {
          word: string;
          translation: string;
          id?: string | null;
        }[]
      | null;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  philosophy?:
    | {
        number: string;
        word: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  founder: {
    eyebrow: string;
    quote: string;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    signatureName: string;
    signatureLocation?: string | null;
  };
  differentiators?:
    | {
        notText: string;
        yesText: string;
        id?: string | null;
      }[]
    | null;
  overview: {
    heading: string;
    image: number | Media;
    facts?:
      | {
          number: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The /contact page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  heading: string;
  intro: string;
  infoRows?:
    | {
        label: string;
        value: string;
        /**
         * Leave blank if not a link.
         */
        href?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  mapCaption?: string | null;
  form?: {
    nameLabel?: string | null;
    contactLabel?: string | null;
    subjectLabel?: string | null;
    messageLabel?: string | null;
    submitLabel?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The /events page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  hero: {
    badge?: string | null;
    headline: string;
    sub: string;
    primaryCtaLabel?: string | null;
    primaryCtaHref?: string | null;
    secondaryCtaLabel?: string | null;
    secondaryCtaHref?: string | null;
    /**
     * Scrolling marquee labels, e.g. "Birthdays", "Corporate Events".
     */
    marqueeItems?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  eventTypes?:
    | {
        image: number | Media;
        number: string;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  venueFeatures?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  customisationGroups?:
    | {
        groupNumber: string;
        groupLabel: string;
        chips?:
          | {
              label: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  enquiryForm?: {
    nameLabel?: string | null;
    eventTypeLabel?: string | null;
    guestCountLabel?: string | null;
    preferredDateLabel?: string | null;
    reachLabel?: string | null;
    moreLabel?: string | null;
    submitLabel?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The /faqs page — 6 categories (Check-in & Checkout, Booking Policies, Farm Dining Bookings, Event Bookings, Add-Ons, Guest Capacity), each with its own Q&A list.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  heading: string;
  sub?: string | null;
  categories?:
    | {
        number: string;
        title: string;
        items?:
          | {
              question: string;
              answer: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The /farm-dining page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "farm-dining".
 */
export interface FarmDining {
  id: number;
  hero: {
    badge?: string | null;
    headline: string;
    sub: string;
    image: number | Media;
    /**
     * e.g. "One seating nightly", "₹1,400 per person"
     */
    facts?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    primaryCtaLabel?: string | null;
    primaryCtaHref?: string | null;
    secondaryCtaLabel?: string | null;
    secondaryCtaHref?: string | null;
  };
  uniquePoints?:
    | {
        number: string;
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  experienceRows?:
    | {
        image: number | Media;
        tagNumber: string;
        tagLabel: string;
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        sizeVariant?: ('default' | 'wide' | 'tall') | null;
        id?: string | null;
      }[]
    | null;
  suitableFor?:
    | {
        title: string;
        body: string;
        image?: (number | null) | Media;
        /**
         * Featured card shows the image as a background; others show just an icon.
         */
        featured?: boolean | null;
        id?: string | null;
      }[]
    | null;
  faqItems?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  reserve?: {
    image?: (number | null) | Media;
    dateLabel?: string | null;
    partySizeLabel?: string | null;
    dietaryLabel?: string | null;
    submitLabel?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  defaultSeoTitle?: T;
  defaultSeoDescription?: T;
  defaultOgImage?: T;
  phone?: T;
  email?: T;
  address?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  logo?:
    | T
    | {
        icon?: T;
        wordmark?: T;
      };
  primaryLinks?:
    | T
    | {
        label?: T;
        href?: T;
        submenu?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  ctaBanner?:
    | T
    | {
        heading?: T;
        body?: T;
        buttonLabel?: T;
        buttonHref?: T;
      };
  brand?:
    | T
    | {
        logo?: T;
        tagline?: T;
        note?: T;
      };
  quickLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  contactInfo?:
    | T
    | {
        label?: T;
        value?: T;
        isLink?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        label?: T;
        href?: T;
        platform?: T;
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  copyrightText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        headline?: T;
        sub?: T;
        backgroundImage?: T;
        primaryCtaLabel?: T;
        primaryCtaHref?: T;
        secondaryCtaLabel?: T;
        secondaryCtaHref?: T;
      };
  staysTeaser?:
    | T
    | {
        heading?: T;
        sub?: T;
        featuredStays?: T;
      };
  experience?:
    | T
    | {
        heading?: T;
        sub?: T;
        items?:
          | T
          | {
              image?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  finalCta?:
    | T
    | {
        heading?: T;
        body?: T;
        buttonLabel?: T;
        buttonHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  manifesto?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        sub?: T;
        primaryCtaLabel?: T;
        primaryCtaHref?: T;
        secondaryCtaLabel?: T;
        secondaryCtaHref?: T;
      };
  story?:
    | T
    | {
        wordGlosses?:
          | T
          | {
              word?: T;
              translation?: T;
              id?: T;
            };
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  philosophy?:
    | T
    | {
        number?: T;
        word?: T;
        body?: T;
        id?: T;
      };
  founder?:
    | T
    | {
        eyebrow?: T;
        quote?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        signatureName?: T;
        signatureLocation?: T;
      };
  differentiators?:
    | T
    | {
        notText?: T;
        yesText?: T;
        id?: T;
      };
  overview?:
    | T
    | {
        heading?: T;
        image?: T;
        facts?:
          | T
          | {
              number?: T;
              label?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  infoRows?:
    | T
    | {
        label?: T;
        value?: T;
        href?: T;
        note?: T;
        id?: T;
      };
  mapCaption?: T;
  form?:
    | T
    | {
        nameLabel?: T;
        contactLabel?: T;
        subjectLabel?: T;
        messageLabel?: T;
        submitLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        headline?: T;
        sub?: T;
        primaryCtaLabel?: T;
        primaryCtaHref?: T;
        secondaryCtaLabel?: T;
        secondaryCtaHref?: T;
        marqueeItems?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  eventTypes?:
    | T
    | {
        image?: T;
        number?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  venueFeatures?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  customisationGroups?:
    | T
    | {
        groupNumber?: T;
        groupLabel?: T;
        chips?:
          | T
          | {
              label?: T;
              id?: T;
            };
        id?: T;
      };
  enquiryForm?:
    | T
    | {
        nameLabel?: T;
        eventTypeLabel?: T;
        guestCountLabel?: T;
        preferredDateLabel?: T;
        reachLabel?: T;
        moreLabel?: T;
        submitLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  heading?: T;
  sub?: T;
  categories?:
    | T
    | {
        number?: T;
        title?: T;
        items?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "farm-dining_select".
 */
export interface FarmDiningSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        headline?: T;
        sub?: T;
        image?: T;
        facts?:
          | T
          | {
              text?: T;
              id?: T;
            };
        primaryCtaLabel?: T;
        primaryCtaHref?: T;
        secondaryCtaLabel?: T;
        secondaryCtaHref?: T;
      };
  uniquePoints?:
    | T
    | {
        number?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  experienceRows?:
    | T
    | {
        image?: T;
        tagNumber?: T;
        tagLabel?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        sizeVariant?: T;
        id?: T;
      };
  suitableFor?:
    | T
    | {
        title?: T;
        body?: T;
        image?: T;
        featured?: T;
        id?: T;
      };
  faqItems?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  reserve?:
    | T
    | {
        image?: T;
        dateLabel?: T;
        partySizeLabel?: T;
        dietaryLabel?: T;
        submitLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}